CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

macro(CreateLibrary)
	
	FILE(GLOB HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/inc/*.hpp")
	FILE(GLOB SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

	ADD_LIBRARY(${PROJECT_NAME} ${SOURCES} ${HEADERS})
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${ARGN})

endmacro(CreateLibrary)
